const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const { calculateVibeIndex, getColorForIndex, getDescriptionForIndex } = require('../src/calculator');
const { generateBadgeUrl, generateBadgeMarkdown } = require('../src/badge');
const { classifyCommit, buildKeywordMatchers } = require('../src/analyzer');
const { replaceBadge, START_MARKER, END_MARKER } = require('../src/updater');
const {
  validateCommitsCount,
  validateCoAuthorMultiplier,
  validateAIKeywords,
  validateBadgeStyle,
  validateBadgeColor,
  validateAssertIndex,
  validateUpdateFiles,
  validateAllInputs,
} = require('../src/validation');

let passed = 0;
let failed = 0;

function test(name, fn) {
  try {
    fn();
    passed++;
    console.log(`  ok   ${name}`);
  } catch (error) {
    failed++;
    console.error(`  FAIL ${name}`);
    console.error(`       ${error.message}`);
  }
}

function approx(actual, expected, name) {
  assert.ok(Math.abs(actual - expected) < 1e-9, `${name}: expected ${expected}, got ${actual}`);
}

const DEFAULT_KEYWORDS = ['Claude', 'GPT', 'AI', 'Agent'];
const matchers = buildKeywordMatchers(DEFAULT_KEYWORDS);

console.log('calculator');

test('100% human -> 10.0', () => {
  const { vibeIndex } = calculateVibeIndex({
    humanPercentage: 100,
    aiPercentage: 0,
    humanCommitsPercentage: 100,
    aiCommitsPercentage: 0,
  });
  approx(vibeIndex, 10, 'vibeIndex');
});

test('100% AI -> 0.0', () => {
  const { vibeIndex } = calculateVibeIndex({
    humanPercentage: 0,
    aiPercentage: 100,
    humanCommitsPercentage: 0,
    aiCommitsPercentage: 100,
  });
  approx(vibeIndex, 0, 'vibeIndex');
});

test('50/50 -> 5.0', () => {
  const { vibeIndex } = calculateVibeIndex({
    humanPercentage: 50,
    aiPercentage: 50,
    humanCommitsPercentage: 50,
    aiCommitsPercentage: 50,
  });
  approx(vibeIndex, 5, 'vibeIndex');
});

test('weighting 60/40 (code 80%, commits 30%)', () => {
  const { vibeIndex } = calculateVibeIndex({
    humanPercentage: 80,
    aiPercentage: 20,
    humanCommitsPercentage: 30,
    aiCommitsPercentage: 70,
  });
  // 0.8 * 0.6 + 0.3 * 0.4 = 0.6 -> 6.0
  approx(vibeIndex, 6, 'vibeIndex');
});

test('color mapping by score', () => {
  assert.strictEqual(getColorForIndex(9), '27ae60');
  assert.strictEqual(getColorForIndex(7), '3498db');
  assert.strictEqual(getColorForIndex(5), 'f39c12');
  assert.strictEqual(getColorForIndex(3), 'e67e22');
  assert.strictEqual(getColorForIndex(1), 'e74c3c');
});

test('description by score', () => {
  assert.strictEqual(getDescriptionForIndex(9), 'Very Human-Centric');
  assert.strictEqual(getDescriptionForIndex(0), 'AI-Heavy');
});

console.log('badge');

test('badge URL uses static/v1 with encoded params', () => {
  const url = generateBadgeUrl({
    label: 'Vibe Index',
    message: '8.5/10.0',
    style: 'flat-square',
    color: '27ae60',
  });
  assert.ok(url.startsWith('https://img.shields.io/static/v1?'), 'base URL');
  assert.ok(url.includes('label=Vibe+Index') || url.includes('label=Vibe%20Index'), 'label encoded');
  assert.ok(url.includes('message=8.5%2F10.0'), 'slash in message encoded');
  assert.ok(url.includes('color=27ae60'), 'color present');
  assert.ok(url.includes('style=flat-square'), 'style present');
});

test('badge URL includes logo when provided', () => {
  const url = generateBadgeUrl({ label: 'X', message: 'Y', logo: 'github' });
  assert.ok(url.includes('logo=github'), 'logo present');
});

test('markdown image, with and without link', () => {
  assert.strictEqual(generateBadgeMarkdown('U', 'Alt'), '![Alt](U)');
  assert.strictEqual(generateBadgeMarkdown('U', 'Alt', 'L'), '[![Alt](U)](L)');
});

console.log('analyzer.classifyCommit');

test('plain human commit', () => {
  const r = classifyCommit({ message: 'fix: correct off-by-one', added: 10, removed: 2 }, matchers);
  assert.strictEqual(r.classification, 'human');
  assert.strictEqual(r.lines, 12);
});

test('"AI" keyword does not match inside ordinary words', () => {
  const r = classifyCommit(
    { message: 'make config available and maintain the email chain', added: 5, removed: 0 },
    matchers
  );
  assert.strictEqual(r.classification, 'human');
});

test('direct AI authorship via keyword', () => {
  const r = classifyCommit({ message: 'Generated by GPT', added: 5, removed: 0 }, matchers);
  assert.strictEqual(r.classification, 'ai');
});

test('co-authored detected from Co-Authored-By trailer', () => {
  const message = 'feat: add feature\n\nCo-Authored-By: Claude <noreply@anthropic.com>';
  const r = classifyCommit({ message, added: 5, removed: 0 }, matchers);
  assert.strictEqual(r.classification, 'co-authored');
});

test('human co-author is not treated as AI', () => {
  const message = 'feat: add feature\n\nCo-Authored-By: Jane Doe <jane@example.com>';
  const r = classifyCommit({ message, added: 5, removed: 0 }, matchers);
  assert.strictEqual(r.classification, 'human');
});

console.log('updater.replaceBadge');

const NEW_BADGE = '![Vibe Index](https://img.shields.io/static/v1?label=Vibe%20Index&message=6.9%2F10.0&color=3498db&style=flat-square)';

test('replaces only content between markers', () => {
  const doc = [
    '# Title',
    START_MARKER,
    '![old](https://img.shields.io/static/v1?label=X&message=1.0&color=red)',
    END_MARKER,
    '',
    '## Examples',
    '![example](https://img.shields.io/static/v1?label=Y&message=2.0&color=blue)',
  ].join('\n');

  const { content, updated } = replaceBadge(doc, NEW_BADGE);
  assert.strictEqual(updated, true);
  assert.ok(content.includes(NEW_BADGE), 'new badge inserted');
  assert.ok(!content.includes('message=1.0'), 'old marked badge replaced');
  assert.ok(content.includes('message=2.0'), 'example badge outside markers untouched');
  // Ampersands in the URL survive verbatim (the sed approach mangled them).
  assert.ok(content.includes('&color=3498db'), 'ampersands preserved');
});

test('idempotent on second run', () => {
  const doc = `${START_MARKER}\nold\n${END_MARKER}`;
  const once = replaceBadge(doc, NEW_BADGE).content;
  const twice = replaceBadge(once, NEW_BADGE);
  assert.strictEqual(twice.updated, false);
  assert.strictEqual(twice.content, once);
});

test('no markers -> no change', () => {
  const doc = '# Just a readme without markers';
  const { content, updated } = replaceBadge(doc, NEW_BADGE);
  assert.strictEqual(updated, false);
  assert.strictEqual(content, doc);
});

console.log('validation');

test('commits-count parsing and bounds', () => {
  assert.strictEqual(validateCommitsCount('500'), 500);
  assert.throws(() => validateCommitsCount('0'));
  assert.throws(() => validateCommitsCount('abc'));
});

test('co-author-multiplier bounds', () => {
  assert.strictEqual(validateCoAuthorMultiplier('0.5'), 0.5);
  assert.throws(() => validateCoAuthorMultiplier('1.5'));
  assert.throws(() => validateCoAuthorMultiplier('-0.1'));
});

test('ai-keywords splitting', () => {
  assert.deepStrictEqual(validateAIKeywords('Claude, GPT ,AI'), ['Claude', 'GPT', 'AI']);
  assert.throws(() => validateAIKeywords(' , '));
});

test('badge-style allow-list', () => {
  assert.strictEqual(validateBadgeStyle('for-the-badge'), 'for-the-badge');
  assert.throws(() => validateBadgeStyle('rounded'));
});

test('badge-color hex and named', () => {
  assert.strictEqual(validateBadgeColor('27ae60'), '27ae60');
  assert.strictEqual(validateBadgeColor('blue'), 'blue');
  assert.throws(() => validateBadgeColor('#27ae60'));
  assert.throws(() => validateBadgeColor('notacolor'));
});

test('assert-index parsing', () => {
  assert.deepStrictEqual(validateAssertIndex('6.0-10.0'), { min: 6, max: 10 });
  assert.strictEqual(validateAssertIndex(''), null);
  assert.throws(() => validateAssertIndex('10-6'));
  assert.throws(() => validateAssertIndex('0-11'));
});

test('update-files parsing (comma and newline separated)', () => {
  assert.deepStrictEqual(validateUpdateFiles('README.md'), ['README.md']);
  assert.deepStrictEqual(validateUpdateFiles('README.md, docs/index.md'), ['README.md', 'docs/index.md']);
  assert.deepStrictEqual(validateUpdateFiles('a.md\n b.md \n'), ['a.md', 'b.md']);
  assert.deepStrictEqual(validateUpdateFiles(''), []);
  assert.deepStrictEqual(validateUpdateFiles(' , '), []);
});

test('validateAllInputs passes through badge-output-file (regression)', () => {
  const result = validateAllInputs({
    commitsCount: '10',
    coAuthorMultiplier: '0.5',
    aiKeywords: 'Claude',
    badgeStyle: 'flat',
    badgeColor: 'blue',
    badgeLogo: 'github',
    assertIndex: '',
    badgeOutputFile: 'badge-url.txt',
    updateFiles: 'README.md, CONTRIBUTING.md',
    includeMessage: 'Vibe Index',
  });
  assert.strictEqual(result.success, true);
  assert.strictEqual(result.validated.badgeOutputFile, 'badge-url.txt');
  assert.strictEqual(result.validated.badgeLogo, 'github');
  assert.deepStrictEqual(result.validated.updateFiles, ['README.md', 'CONTRIBUTING.md']);
});

console.log('integration (action entry point)');

test('badge is updated even when the assertion fails', () => {
  const repoRoot = path.join(__dirname, '..');
  const tmpFile = path.join(__dirname, '.tmp-assert-target.md');
  const placeholder = '![Vibe Index](https://img.shields.io/static/v1?label=Vibe%20Index&message=PLACEHOLDER&color=lightgrey)';
  fs.writeFileSync(tmpFile, `# Tmp\n${START_MARKER}\n${placeholder}\n${END_MARKER}\n`);

  let status = 0;
  try {
    // assert-index 10.0-10.0 fails for any repo that isn't 100% human, which
    // forces the failure path; the badge must still be written first.
    execFileSync('node', ['src/index.js'], {
      cwd: repoRoot,
      env: {
        ...process.env,
        'INPUT_COMMITS-COUNT': '50',
        'INPUT_ASSERT-INDEX': '10.0-10.0',
        'INPUT_UPDATE-FILES': tmpFile,
      },
      stdio: 'ignore',
    });
  } catch (err) {
    status = err.status;
  }

  try {
    const content = fs.readFileSync(tmpFile, 'utf-8');
    assert.strictEqual(status, 1, 'action should fail the assertion (exit 1)');
    assert.ok(!content.includes('PLACEHOLDER'), 'badge was updated despite the failure');
    assert.ok(content.includes('shields.io/static/v1'), 'a real badge URL is present');
  } finally {
    fs.unlinkSync(tmpFile);
  }
});

console.log(`\n${passed} passed, ${failed} failed`);
if (failed > 0) {
  process.exit(1);
}
